# Generated by Django 5.0.3 on 2024-03-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='college',
            field=models.CharField(max_length=32, null=True, verbose_name='学院'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sex',
            field=models.IntegerField(null=True, verbose_name='性别'),
        ),
    ]
