# Generated by Django 5.0.3 on 2024-03-31 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_teacher_college_alter_teacher_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitesign',
            name='allow_count',
            field=models.IntegerField(default=10, verbose_name='允许访问次数'),
        ),
        migrations.AddField(
            model_name='invitesign',
            name='count',
            field=models.IntegerField(default=0, verbose_name='已访问次数'),
        ),
    ]
