# Generated by Django 5.0.3 on 2024-04-01 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_student_email_teacher_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.SmallIntegerField(null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sex',
            field=models.SmallIntegerField(null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='idnumber',
            field=models.CharField(help_text='学号或教师号', max_length=32, verbose_name='证件号'),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.userinfo', verbose_name='管理者')),
            ],
        ),
    ]
