# Generated by Django 5.0.3 on 2024-04-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_student_sex_alter_teacher_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='sex',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], null=True, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profession',
            field=models.SmallIntegerField(choices=[(1, '教师'), (2, '导员'), (3, '教授'), (4, '副教授')], default=1, verbose_name='职称'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sex',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], null=True, verbose_name='性别'),
        ),
    ]
