# Generated by Django 5.0.3 on 2024-04-01 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_manager_sex_teacher_profession_alter_student_sex_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='desc',
        ),
    ]
