# Generated by Django 5.0.3 on 2024-04-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_remove_course_day_remove_course_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='join_counts',
            field=models.IntegerField(default=0, verbose_name='已参加人数'),
        ),
    ]
