# Generated by Django 5.0.3 on 2024-04-02 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_course_join_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_sign',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.course', verbose_name='签到课程'),
        ),
        migrations.AlterField(
            model_name='course_sign',
            name='end_datetime',
            field=models.DateTimeField(verbose_name='结束时间'),
        ),
    ]
