# Generated by Django 5.0.3 on 2024-04-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_course_sign_course_alter_course_sign_end_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_cords',
            name='sign',
            field=models.IntegerField(choices=[(1, '已签到'), (2, '未签到')], default=2, verbose_name='签到'),
        ),
        migrations.AlterField(
            model_name='course_sign',
            name='sign_counts',
            field=models.IntegerField(default=0, verbose_name='签到人数'),
        ),
    ]
