# Generated by Django 5.0.3 on 2024-04-02 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_course_cords_course_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_cords',
            name='course_sign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.course_sign', verbose_name='课程签到'),
        ),
    ]
