# Generated by Django 5.0.3 on 2024-04-02 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_course_cords_course_sign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_waring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, '已处理'), (2, '未处理')], default=2, verbose_name='处理状态')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='警告时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.userinfo', verbose_name='发起人')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.student', verbose_name='警告者')),
            ],
        ),
    ]
