# Generated by Django 5.0.3 on 2024-04-03 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_student_waring_course_alter_student_classes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_waring',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.course', verbose_name='警告课程'),
        ),
    ]
