# Generated by Django 5.0.3 on 2024-04-03 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_student_waring_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_sign',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.course', verbose_name='签到课程'),
        ),
    ]
