# Generated by Django 5.0.3 on 2024-04-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_course_sign_code_alter_course_sign_loaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_sign',
            name='code',
            field=models.CharField(help_text='可选', max_length=4, null=True, verbose_name='签到口令'),
        ),
        migrations.AlterField(
            model_name='course_sign',
            name='distance',
            field=models.IntegerField(help_text='半径(m)', null=True, verbose_name='签到距离'),
        ),
    ]
